spring:
  profiles:
    group:
      default: common, default
      dev: common, dev
      prd: common, prd
    active: default
---
spring:
  config:
    activate:
      on-profile: common
  application:
    name: api-service
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  packages-to-scan: com.api
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operations-sorter: alpha
    tags-sorter: alpha

server:
  port: 9011
  servlet:
    context-path: /api/movie

jpa:
  entity-packages: com.api.**.entity

jwt:
  access-token-secret-key: access-secret-key-access-secret-key
  refresh-token-secret-key: refresh-secret-key-refresh-secret-key
  access-token-expiration-time: 120
  refresh-token-expiration-time: 604800

request:
  cookie:
    refresh-cookie-name: MOVIE_REFRESH-TOKEN
    secure: false # prd: true
    same-site: Lax

google:
  client-id: ${GOOGLE_CLIENT_ID:-unsed}
  client-secret: ${GOOGLE_CLIENT_SECRET:-unused}

logging:
  file:
    path: ./logs
  charset:
    console: UTF-8
    file: UTF-8

security:
  secret-key: AES
  algorithm: U#(&^#*NAd123

---
spring:
  config:
    activate:
      on-profile: default
    import:
      - classpath:config/default/config.yml
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - classpath:config/dev/config.yml
---
spring:
  config:
    activate:
      on-profile: prd
    import:
      - classpath:config/prd/config.yml
